image:
  - Windows Server 2012 R2

build: false

test_script:
  - ps: Install-Module Datum -Verbose
  - ps: . .\build.ps1 -ResolveDependency

environment:
  NuGetApiKey:
    secure: Wt2Q6bJg+ozZ24LUyGSlYaj1RDpfh+A4s7JhKfqhY2KfbU30rv5EmgnJptiRlXWL

skip_commits:
  message: /updated doc.*|update doc.*s/
